### ISSUE TITLE
problems running

### ISSUE THREAD

**Issue by lonnietc** [SebastiaanKlippert/go-wkhtmltopdf#1]
Hello,

I have download and tried to compile your basic wrapper for wkhtmltopdf with your code:

package wkhtmltopdf

import (
    "fmt"
    "log"
)

func ExampleSimple() {

    pdfg, err := NewPDFGenerator()
    if err != nil {
        log.Fatal(err)
    }

    pdfg.AddPage(NewPage("https://github.com/SebastiaanKlippert/go-wkhtmltopdf"))
    err = pdfg.Create()
    if err != nil {
        log.Fatal(err)
    }
    err = pdfg.WriteFile("./simplesample.pdf")
    if err != nil {
        log.Fatal(err)
    }
    //Or to use the raw PDF data
    //pdf := pdfg.Bytes()
------------------------------------

but am getting an error:

spartan:~/work/go-wkhtmltopdf$ go build
# _/home/lonnie/work/go-wkhtmltopdf
./main.go:4: imported and not used: "fmt"
./main.go:10: undefined: NewPDFGenerator
./main.go:15: undefined: NewPage

Can you please advise on how to fix this?

Thanks,
Lonnie

**Comment by SebastiaanKlippert** [comment]
Hi, 

The function ExampleSimple is a godoc example function. 
https://golang.org/pkg/testing/#hdr-Examples
It was renamed for the readme, the funcion in simplesample_test.go is a working sample. 

The example functions are written in the same package and therefore no package name is included before the functions. 
The easiest way to test the example is to run it as a go test  or to write a main package and call the Example function  from your main function. In that case you can call wkhtmltopdf.NewPDFGenerator and wkhtmltopdf.NewPage after importing the wkhtmltopdf package.
