### ISSUE TITLE
Warning: Blocked access to file C:/Users/Administrator/....

### ISSUE THREAD

**Issue by sicuni** [SebastiaanKlippert/go-wkhtmltopdf#101]
Warning: Blocked access to file C:/Users/Administrator/...
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown

Local images that read html from local files do not seem to be supported.
Are there some other solutions?

**Comment by sicuni** [comment]
I changed the wkhtmltopdf version from 0.12.6 to 0.12.5.
Problem solved

**Comment by SebastiaanKlippert** [comment]
You did not have to downgrade, you need to set `page.EnableLocalFileAccess(true)`
