### ISSUE TITLE
ResetPages() does not clear buffers

### ISSUE THREAD

**Issue by martinlindenberg** [SebastiaanKlippert/go-wkhtmltopdf#102]
Hey

i'm using go-wkhtmltopdf in a lambda function to generate pdfs. 
It works fine until the lambda container is re-used for another pdf generation.

To avoid issues i was calling `pdfg.ResetPages()` which looks on the first sight like the proper solution.
After some time i found out that the generated file size increased and that some pdf readers start showing the data of the first execution and some printers print out multiple pages.

To fix this i'm now additionally calling `pdfg.Buffer().Reset()` together with `pdfg.ResetPages()`

Question now:
To me it looks a bit misleading that ResetPages() does not reset all page data - should the Buffer().Reset() be internally included in that ResetPages() function ?

**Comment by SebastiaanKlippert** [comment]
I think I will just reset it every time it writes to the buffer on Create() or CreateContext() then it is always safe for reuse.

Also, I am a bit surpised with this behaviour on Lambda. We use it with Docker Lambda's as well but our code creates a new generator using `wkhtmltopdf.NewPDFGenerator()` for every PDF anyway so the buffer is not reused. Performance wise this is OK, the lookup of wkhtmltopdf on the system is the heaviest part and that is cached by the package internally in a global variable. So you could just create a new instance each time as a workaround.
Are using global variables to store the state between executions?

**Comment by martinlindenberg** [comment]
It is running on AWS lambda for me. 

I think the reason why it behaves like this, is that i am only initiating the PDF Generator once per lambda container.
The main() function contains this line (and some additional configs...) 
`pdfg, err := wkhtmltopdf.NewPDFGenerator()`
It is only called once per container initialization and keeps that object in memory.

The handler function uses the following function to render the pdf
```
func (h handler) renderPdf() ([]byte) {
  h.pdfgen.ResetPages()
  h.pdfgen..Buffer().Reset()                 // added

  h.pdfgen.AddPage(page)
  h.pdfgen.Create()
  return h.pdfgen.Bytes()
}
```

So it is not stored in global variables or anything - it just lives in the initiated containers memory.

**Comment by SebastiaanKlippert** [comment]
Hi,

Thanks for explaining. In this case the PDF Generator object is indeed reused. Everything you declare in main is kept in memory as `Lambda.Start()` never returns, it just calls your handler (renderPdf()) for each invocation. Similar to `http.ListenAndServe` 

To make the behaviour of this package more predictable the buffer is now cleared before each run where the output will be written to the buffer. 
https://github.com/SebastiaanKlippert/go-wkhtmltopdf/releases/tag/v1.8.0

**Comment by martinlindenberg** [comment]
thanks for the fast reaction :+1:
