### ISSUE TITLE
undefined: exec.ErrDot

### ISSUE THREAD

**Issue by liuyu1996** [SebastiaanKlippert/go-wkhtmltopdf#103]
My go version is 1.18,prompt error:"undefined: exec.ErrDot"
`path, err = lookPath(filepath.Join(dir, exe))
if errors.Is(err, exec.ErrDot) {
		return err
}`

**Comment by SebastiaanKlippert** [comment]
I see. That error is only available on go 1.19, let me fix that.

**Comment by SebastiaanKlippert** [comment]
Coming back to what I just said, I will not fix this.

You can either use go >1.19 with the latest version or use the previous version https://github.com/SebastiaanKlippert/go-wkhtmltopdf/releases/tag/v1.7.1 
`go get github.com/SebastiaanKlippert/go-wkhtmltopdf@v1.7.1`
