### ISSUE TITLE
Margin setting support mm

### ISSUE THREAD

**Issue by zjkyz8** [SebastiaanKlippert/go-wkhtmltopdf#106]
Currently, margin only support set based on centimeter， can we make it support millimeter？

**Comment by SebastiaanKlippert** [comment]
Hi, I don;t actually know what the unit is, I though it was already in mm.
But I do admit that there was a mistake when I created this, the margin and page size are documented as type "unitreal" If read that as "uintreal" or something, so you could indeed specifiy something like `15mm` or `15cm` in wkhtmltopdf but this was only flagged as an issue once before so I think most people are happy with just specifying 0.1 for 1mm.
It would be a breaking change to change the type, I could add six new options as string, something like `MarginBottomString` (not sure of the name yet) but that would take a while before I have some time.
I wll look into it 👍

**Comment by SebastiaanKlippert** [comment]
The unit was already in mm as I thought otherwise it would have been a problem, centimeters are not granular enough.
But I just created a new reslease that also allows it to be set with unit (as a string value). See https://github.com/SebastiaanKlippert/go-wkhtmltopdf/releases/tag/v1.9.0
