### ISSUE TITLE
"built against an unpatched version of QT" with active TOC

### ISSUE THREAD

**Issue by galax3** [SebastiaanKlippert/go-wkhtmltopdf#108]
Hi, I'm using version 1.9.0 and receive the following error when I activate toc (pdfg.TOC.Include = true).

`This version of wkhtmltopdf is built against an unpatched version of QT, and does not support more than one input document.
Exit with code 1, due to unknown err`

Even with the exact code copied from here:
https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/86#issuecomment-1142579701

```
pdfg, err := NewPDFGenerator()
if err != nil {
	t.Fatal(err)
}

pdfg.AddPage(NewPage("https://www.google.com"))

pdfg.TOC.Include = true

err = pdfg.Create()
if err != nil {
	t.Fatal(err)
}
```

err = pdfg.Create() throws the error

Any ideas?
Thank you

**Comment by SebastiaanKlippert** [comment]
What wkhtmltopdf are you using? I guess it is an older one, 0.12.6 should work.

**Comment by galax3** [comment]
I have 0.12.6 in place. Updated debian 11 running

**Comment by galax3** [comment]
short update: I fixed the issue by deinstalling the debian repo version and installing the package from the original website. Thanks anyway
