### ISSUE TITLE
Go get not working for  v1.9.0 Feb 11, 2023 

### ISSUE THREAD

**Issue by julian59189** [SebastiaanKlippert/go-wkhtmltopdf#110]
v1.8.2 is working

**Comment by julian59189** [comment]
go1.19.4

**Comment by SebastiaanKlippert** [comment]
Any more details you can give? It works fine when I just tested it (with go 1.20).

**Comment by julian59189** [comment]
I am getting this:
`go: github.com/SebastiaanKlippert/go-wkhtmltopdf@v1.9.0: reading https://<private-proxy>/github.com/%21sebastiaan%21klippert/go-wkhtmltopdf/@v/v1.9.0.info: 404 Not Found`

Or this when I use lowercase letters because the path looked odd.
`go: github.com/sebastiaanklippert/go-wkhtmltopdf@v1.9.0: reading https:<private-proxy>/github.com/sebastiaanklippert/go-wkhtmltopdf/@v/v1.9.0.info: 404 Not Found`

It could also be our go-proxy. But every other package I tried worked and also 1.8.2 worked.

**Comment by julian59189** [comment]
Btw also tried now with go1.20. Same issue, but as said above: Could also be on our end. Especially if nobody else is facing the same problems

**Comment by SebastiaanKlippert** [comment]
@chgz Are you also using a proxy?
I don't really know what could be the cause of this issue so I also don't know how to fix it.
If it is only with a proxy I can test that myself. So any errors you see etc, would be helpful.

**Comment by julian59189** [comment]
Yeah it is a proxy. I guess if nobody else has the problem we can close it

**Comment by julian59189** [comment]
@SebastiaanKlippert did you ever overwrite 1.9.0?

**Comment by SebastiaanKlippert** [comment]
No, still the same.
I could create a 1.9.1, I did accept a merge request.

**Comment by SebastiaanKlippert** [comment]
v1.9.1 is now available

**Comment by mandhana-ayush** [comment]
@SebastiaanKlippert Is this package compatible with go 1.18.10

I am getting this error
..\go\pkg\mod\github.com\!sebastiaan!klippert\go-wkhtmltopdf@v1.9.1\wkhtmltopdf.go:287:25: undefined: exec.ErrDot
note: module requires Go 1.19

**Comment by SebastiaanKlippert** [comment]
@mandhana-ayush No the latest version is not, you need 1.19 or later.
But you can use v1.7 or earlier of this package for older Go versions. `go get github.com/SebastiaanKlippert/go-wkhtmltopdf@v1.7.1`
