### ISSUE TITLE
PDF has blank pages from second page onwards

### ISSUE THREAD

**Issue by omkar-equinix** [SebastiaanKlippert/go-wkhtmltopdf#119]
Using wkhtmltopdf version: 1.7.0 and also 1.9.1

As per the observation, on generating expected html which has all the required data to populate in our pdf but if the `html.Len()` in the `page := wkhtmltopdf.NewPageReader(html)` is more than 26474999, the go-wkhtmltopdf generates a pdf in which data from second page is blank.

Found some similar issue in [#25](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/25) & [#118](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/118) and even tried the solution mentioned in the discussions but the issue still persist.

It looks like the issue is mainly due to large data since the total number of pages in the pdf is also more than 2100.

**Comment by omkar-equinix** [comment]
Hi,

On trying to read the same file using `wkhtmltopdf.NewPage()` where the argument to NewPage method is html.String() I am getting an error as _argument list too long_

**Comment by SebastiaanKlippert** [comment]
In that case you need to save the HTML to a file and use the path to the file as argument to NewPage.

If you could try that it would be very helpful. I will investigate this in the weekend, but I am not sure if I can reproduce it.

**Comment by SebastiaanKlippert** [comment]
I have not been able to reproduce this. But I just did a simple test with repeating the HTML multiple times.
It looks like this package does not have any limits to the size of the input and it feeds everything to stdin without issues.

So any limits you encounter are most likely to be in wkhtmltopdf itself and I cannot fix that.
