### ISSUE TITLE
css file not rendering While converting html to pdf 

### ISSUE THREAD

**Issue by MuthukumarHelios** [SebastiaanKlippert/go-wkhtmltopdf#13]
HI @SebastiaanKlippert 

**My current Work**

--> it is working fine 

```
var StudenthtmlStr string = "<html>  <head>
        <style>
        h1 {color:red;}
        p {color:blue;}
        </style>
        </head>
       <body background="{{image1}}">
       <h1>This is an html from pdf to test color<h1>
        </html>"
```
**My expectation**

> ### Instead of writing the css in the variable i have to link my external *.css file

```
var StudenthtmlStr string = "<html>  <head>
        <style>
  <link rel "stylesheeet" href="mycssfile.css">  //Not working in our Plugin      
    </style>
        </head>
       <body background="{{image1}}">
       <h1>This is an html from pdf to test color<h1>
        </html>"
```

**Comment by SebastiaanKlippert** [comment]
Hi,

I think this is more a wkhtmltopdf question, I only provide a golang interface to it.
You may be looking for the `--user-style-sheet` option, with that you can pass in a local CSS file. This option can be set using my Go package, but I have not tried it myself.

If you have any issues, their github is at https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by MuthukumarHelios** [comment]
How to apply `--user-style-sheet` is it possible to achieve my case in our plugin

**Comment by MuthukumarHelios** [comment]
`wkhtmltopdf -V
wkhtmltopdf 0.12.2.4`

**the Below command working fine in the terminal**
I think it is possible to achieve in our code 

`wkhtmltopdf --user-style-sheet hello.css student.html heyther.pdf`

**Comment by MuthukumarHelios** [comment]
[see line ](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/blob/master/wkhtmltopdf.go#L99)
It is possible to give the input.css file
