### ISSUE TITLE
Setting footer parameters

### ISSUE THREAD

**Issue by philiplb** [SebastiaanKlippert/go-wkhtmltopdf#15]
Hi,
thank you for this wrapper. :)
On the CLI, I use these parameters:
```bash
--footer-right [page]  --footer-font-size 9
```
How could I set them with go-wkhtmltopdf?

**Comment by SebastiaanKlippert** [comment]
Hi,

You need to set the footer options for each "page" individually.
A page in wkhtmltopdf is an input document, not the page in the output.

So you could do something like this.
```go

// create PDF generator
pdfg, err := wkhtmltopdf.NewPDFGenerator()
if err != nil {
	return err
}

// add one input page with its options
page1 := wkhtmltopdf.NewPage("https://www.google.com")
page1.FooterRight.Set("[page]")
page1.FooterFontSize.Set(9)

pdfg.AddPage(page1)
	
// create PDF
err = pdfg.Create()
if err != nil {
	return err
}
```

**Comment by philiplb** [comment]
Works perfectly fine, thank you! :)
