### ISSUE TITLE
Sending the PDF to a real printer

### ISSUE THREAD

**Issue by gedw99** [SebastiaanKlippert/go-wkhtmltopdf#18]
Curious if you got the chain so that that after the pdf is generated you could also bring up the system print dialog to print the file ?

**Comment by SebastiaanKlippert** [comment]
Not really, printing is platform specific.
We have a Windows client, there we use PDFium to render to printer directly using windows DLL calls.
In our web application we use PDF.js to let the client handle printing.

If you render the PDF client side anyway, you could consider not creating a PDF at all and use  wkhtmltoimage to create a (bitmap) image which you can print directly.
My wrapper does not support wkhtmltoimage yet, although I have been considering it.

**Comment by gedw99** [comment]
Thanks this is really helpful

I will try out the approaches you suggested.
Any sample code links that you know are helpful but will forge ahead anyway.
Maybe put into your repo to help other too ??
