### ISSUE TITLE
Not sure if it finds wkhtmltopdf

### ISSUE THREAD

**Issue by allochi** [SebastiaanKlippert/go-wkhtmltopdf#2]
Hi,

I tried all the path instructions including copying `wkhtmltopdf` to the directory where the Go program resides, but the program always generate a pdf of size 366kb, which doesn't open, and exit with no error.

Could you please help. Thanks!

**Comment by SebastiaanKlippert** [comment]
Hi,

Do you have more info on the OS you use and maybe the PDF it generates? Or some sample code?
I have never seen a 366KB PDF before. 

If wkhtmltopdf is not found you should get error "wkhtmltopdf not found" on NewPDFGenerator() so I do not think that is the problem.
Perhaps you input is corrupt, do use an URL (Page) or buffer (PageReader) as input?

**Comment by allochi** [comment]
Hi @SebastiaanKlippert, sorry didn't get to you earlier, long working day. I'm using OS X and Go 1.6.2, wkhtmltopdf 0.12.3 in the directory where the Go program is. Thanks for your help.

```go
package main

import (
	"fmt"
	"log"

	"github.com/SebastiaanKlippert/go-wkhtmltopdf"
)

func main() {

	// Create new PDF generator
	pdfg, err := wkhtmltopdf.NewPDFGenerator()
	if err != nil {
		log.Fatal(err)
	}

	// Add one page from an URL
	pdfg.AddPage(wkhtmltopdf.NewPage("http://www.google.com"))

	// Create PDF document in internal buffer
	err = pdfg.Create()
	if err != nil {
		log.Fatal(err)
	}

	// Write buffer contents to file on disk
	err = pdfg.WriteFile("./sample.pdf")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Done")
	// Output: Done
}
```

**Comment by SebastiaanKlippert** [comment]
Your code looks fine.

I don't have access to an OS X test machine (yet, will have a dedicated one next week), but I have added an osx test on Travis CI. 
And I think I may have found your problem, not setting an explicit filemode and  acces rights in WriteFile does not allow you to open the file on OS X but it does on Windows and Linux. I have made that mistake with other packages before :sweat: 

For some reason test ```TestGeneratePdfFromStdinHtml5``` takes a very long time on osx and it generates 6623 pages in the PDF (which gets up to 7MB). But I think that is more of a wkhtmltopdf issue with that HTML5 file and possibly only on OS X. I will look into that later.
Other files run fine and thay also use google.com as input.

You can see the latest run at https://travis-ci.org/SebastiaanKlippert/go-wkhtmltopdf/builds/147509589 

Let me know if the file permissions solved your problem.

**Comment by allochi** [comment]
This worked :), Thanks a lot!

**Comment by SebastiaanKlippert** [comment]
Glad to hear that and thanks for reporting it.
