### ISSUE TITLE
Add multiple pages make blank pages

### ISSUE THREAD

**Issue by ghost** [SebastiaanKlippert/go-wkhtmltopdf#21]
Hi, I try with your library add pages in loop, but still I get only first page and other are blank only footer are there and what I check in debugger pages are correctly added to pages slice in library but generate wrong output, could you help me ?

my code:

```
// loop
for _, pageData := range *dataForPages {
patient := Patient{}.NewV0(*pageData, 39)
buf := parseAndGetHtml(patient, brand) // return bytes.Buffer which return correct bytes
page := setupAndGetPage(&buf)
pdfg.AddPage(page)
}
// prepare page 
func setupAndGetPage(buf *bytes.Buffer) (*wkhtmltopdf.PageReader) {
	page := wkhtmltopdf.NewPageReader(bytes.NewReader(buf.Bytes()))
	page.FooterFontName.Set("helvetica")
	page.FooterFontSize.Set(8)
	page.HeaderFontName.Set("helvetica")
	page.HeaderFontSize.Set(10)
	page.FooterRight.Set("[page]/[topage]")
	page.Zoom.Set(1.25)
	page.PrintMediaType.Set(true)

	return page
}

// make template
func parseAndGetHtml(patient *Patient, brand string) (bytes.Buffer) {
	tpl := template.Must(template.ParseGlob(fmt.Sprintf("pdfTemplates/%s/*.gohtml", brand)))

	buf := bytes.Buffer{}
	err := tpl.ExecuteTemplate(&buf, "index.gohtml", patient)
	if err != nil {
		log.Fatal(err)
	}

	return buf
}
```

**Comment by SebastiaanKlippert** [comment]
Hi,

As stated in both the readme and GoDoc for [PageReader](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PageReader), you can only add one input from StdIn.
This is just the way that wkhtmltopdf works.

Also note that what wkhtmltopdf calls a page, is in fact an input HTML document. Not a page in output. A single HTML input, can produce multiple pages in the PDF output.

If you really need to have multiple input documents in one PDF you could start a Go server the serve the documents using a GET method or just create a big HTML document  in your loop and add the documents to a buffer before adding them as a single input.

**Comment by chris-freightweb** [comment]
More info here:
https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/54
