### ISSUE TITLE
set footer doesn't work

### ISSUE THREAD

**Issue by flrnt** [SebastiaanKlippert/go-wkhtmltopdf#26]
```go
        // ...
	page := wkhtmltopdf.NewPageReader(strings.NewReader(tpl.String()))
	page.FooterRight.Set("[page]")
	page.FooterFontSize.Set(10)
	pdf.AddPage(page)
	
	errors := pdf.Create()
        // ...
```
Can't figure out what I'm missing to add footer in my page. Any clue ? The only page generated is OK but there is no footer at all

**Comment by flrnt** [comment]
Sorry for the late update but it doesn't seems to work. Footer does not appear even with a simple : 
```go
page := NewPage("https://www.google.com")
page.FooterRight.Set("[page]")
page.FooterFontSize.Set(10)
```

**Comment by grmat** [comment]
I have the same issue with wkhtmltopdf 0.12.5

**Comment by SebastiaanKlippert** [comment]
I have added [this test](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/blob/master/wkhtmltopdf_test.go#L182) which [installs wkhtmltopdf 0.12.5](https://travis-ci.org/SebastiaanKlippert/go-wkhtmltopdf/jobs/490711125#L638) and then produces [this PDF](https://sklippert-eu-west.s3-eu-west-1.amazonaws.com/SebastiaanKlippert/go-wkhtmltopdf/106/106.2/testfiles/TestSetFooter.pdf) which prints the footer as expected.
The same happens on my Windows 10 machine with 0.12.5 and 0.12.4

So any issue you are facing is most likely not in this package, but probably a wkhtmltopdf issue.

@grmat Can you run the same test and post the output?

**Comment by grmat** [comment]
Thanks for your response.

I've just ran the test and this is the result:

[TestSetFooter.pdf](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/2847100/TestSetFooter.pdf)

**Comment by SebastiaanKlippert** [comment]
Thanks for testing anyway, it is an interesting problem, best to report it at https://github.com/wkhtmltopdf/wkhtmltopdf and include your OS version.

**Comment by Limero** [comment]
I have the same problem on Arch Linux with wkhtmltopdf 0.12.5. Did anyone create an upstream bug report?

**Comment by Limero** [comment]
I tried running wkhmltopdf directly from the terminal with a footer option and got an error message `The switch --footer-right, is not support using unpatched qt, and will be ignored.`.

After replacing the official Arch Linux [wkhtmlpdftopdf package](https://www.archlinux.org/packages/community/x86_64/wkhtmltopdf/) with [wkhtmltopdf-static](https://aur.archlinux.org/packages/wkhtmltopdf-static/) it works as it should.

**Comment by SebastiaanKlippert** [comment]
Good info, thanks a lot. Never used that version of wkhtmltopdf.
