### ISSUE TITLE
Write to buffer

### ISSUE THREAD

**Issue by IvanDelsinne** [SebastiaanKlippert/go-wkhtmltopdf#29]
I didn't find any direct way, so here's my question: Is there any good way to directly write to a Writer buffer?

The context is to generate a PDF and directly send it through the http.ResponseWriter.

**Comment by SebastiaanKlippert** [comment]
Hello,

This was not possible, but it sound like a nice feature.

If have added a [SetOutput](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.SetOutput) method that will accept an `io.Writer` so you can write directly to a file or http.ResponseWriter.

Let me know if that helps then I will create a new release.

**Comment by IvanDelsinne** [comment]
Definitely looks useful

**Comment by SebastiaanKlippert** [comment]
Released in [v1.3.0](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/releases/tag/v1.3.0)
