### ISSUE TITLE
Regarding ViewportSize

### ISSUE THREAD

**Issue by allochi** [SebastiaanKlippert/go-wkhtmltopdf#3]
When using `wkhtmltopdf` directly I can set the `--viewport-size` like so:

```basg
./wkhtmltopdf --viewport-size 1920x1080 -L 0 -R 0 -T 0 -B 0 http://www.google.com sample.pdf
```

I can use the format `1920x1080`, but not with `go-wkhtmltopdf`, because it expect `uint`, I was able to achieve the required result for now by using 

```go
page.ViewportSize.Set(1920)
```

but I think this will come up in the future and it needs to be fixed.

Thanks @SebastiaanKlippert, you package has proven to be quit useful, we are using it now in IDMC http://www.internal-displacement.org, you can list us if you would like to.

**Comment by allochi** [comment]
Sorry to add to this, but setting the margins didn't work too

```go
pdfg.MarginLeft.Set(0)
pdfg.MarginTop.Set(0)
pdfg.MarginRight.Set(0)
pdfg.MarginBottom.Set(0)
```

doesn't give the same result as `-L 0 -R 0 -T 0 -B 0`

**Comment by SebastiaanKlippert** [comment]
Wow I was just looking into this with a co-worker who is designing our lay-outs and he is experiencing similar issues.

For MarginLeft etc. I use the long option --margin-left which should do the same as -L according to http://wkhtmltopdf.org/usage/wkhtmltopdf.txt 
If that is not the case this looks like a wkhtmltopdf issue, but I could also use -L there.
I will test this today.

Regarding the viewport size: I think this is something I have overlooked, this should probably just be a string option, not an uint. I will also test this today and change it where needed.

Thanks for reporting again :+1:

**Comment by SebastiaanKlippert** [comment]
Update: 
The viewport size is now a string option, you can set it like this ```page1.ViewportSize.Set("3840x2160")```

The margins are a stupid bug, I ignore 0 values... So they are skipped when set to 0. I am thinking of a fix now, but that probably means I have to store the internal uint option as a pointer to see if they are set or use a boolean value to check if set.

**Comment by SebastiaanKlippert** [comment]
I have added an internal bool variable for int and float options, so setting the margin to 0 should be possible now.

Thanks again for your feedback and nice to hear you are happy with it.

**Comment by allochi** [comment]
This is cool, thanks @SebastiaanKlippert, I will update my project sometime today. 

I'm not sure if you intent to also support PNG in the future? I'm sorry if I it already does and I missed it.

**Comment by SebastiaanKlippert** [comment]
Maybe, I intended to do so when I started this package and wkhtmltoimage only takes a few options so that would not not be much effort to add.
I am guessing we need it ourselves soon for our API, so I think this will probably be added (very) soon.

**Comment by allochi** [comment]
Thanks @SebastiaanKlippert, I will keep an eye :)
