### ISSUE TITLE
GAE problem

### ISSUE THREAD

**Issue by gspartners** [SebastiaanKlippert/go-wkhtmltopdf#31]
What do I do if I use Google App Engine?
The binary file wkthmltopdf is too big to upload. They have a maximum of 32MB, but the binary files is almost 40MB.

**Comment by SebastiaanKlippert** [comment]
Hi,

I cannot control the size of wkhtmltopdf, you could ask at https://github.com/wkhtmltopdf/wkhtmltopdf

I am no App Engine expert, but from [this issue](https://issuetracker.google.com/issues/112061972) I understand the size limit for Go is 64MB (Go just has bigger binaries) but I don't know if that is just one binary and if you can upload multiple (wkhtmltopdf is not written in Go).

I would think that running a Docker [custom runtime](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/about-custom-runtimes) is a better solution, but I have no experience with this in GAE.

It is in my backlog to provide a Docker file and/or image for this project at some point in the near future, but my agenda is a bit full at the moment.
