### ISSUE TITLE
"wkhtmltopdf not found" error

### ISSUE THREAD

**Issue by masterleem** [SebastiaanKlippert/go-wkhtmltopdf#33]
The error only happens in linux environment, where as it has no problems running on the latest mac os (mojave). Snippet below:

`package main

import (
  "github.com/SebastiaanKlippert/go-wkhtmltopdf"
  "log"
)

func main() {
  page := wkhtmltopdf.NewPage("https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf")
  pdfg, err := wkhtmltopdf.NewPDFGenerator()
  if err != nil {
    log.Fatal("error:",err.Error())
  }

  pdfg.AddPage(page)
  if err = pdfg.Create(); err != nil {
    log.Fatal("say what? ",err)
  }

  if err = pdfg.WriteFile("test.pdf"); err != nil {
    log.Fatal(err.Error())
  }
  fmt.Println("Done")
}`

Linux go env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"

Macos go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"

**Comment by SebastiaanKlippert** [comment]
Thanks for listing the environment variables, but I am not seeing where `wkhtmltopdf` itself is located.

It is found as described in https://github.com/SebastiaanKlippert/go-wkhtmltopdf#installation 

> go-wkhtmltopdf finds the path to wkhtmltopdf by
>
> - first looking in the current dir
> - looking in the PATH and PATHEXT environment dirs
> - using the WKHTMLTOPDF_PATH environment dir
>
> If you need to set your own wkhtmltopdf path or want to change it during execution, you can call SetPath().

For all these options I use [exec.LookPath](https://golang.org/pkg/os/exec/#LookPath) from the standard library, so make sure it is in there and the executable permissions are set.

The reason it works in one environment and not the other can be any number of things, maybe it is not in your PATH or maybe you are not running the version you think.

If you need more help I need to know from which location you want to run the `wkhtmltopdf` binary (which needs to be called exactly that).

**Comment by masterleem** [comment]
Thanks for the reply, I have found the root of the issue and it's now resolved.

**Comment by Estebmaister** [comment]
I have a similar problem, it fails when tries to get the path, someone can tell me what is the path in windows? to set it manually.

**Comment by SebastiaanKlippert** [comment]
>  someone can tell me what is the path in windows

That depends on how you installed wkhtmltopdf, if you used the installer it is in `C:/Program Files/wkhtmltopdf/bin/` or `C:/Program Files (x86)/wkhtmltopdf/bin/` for the 32 bit version. If you donwloaded it from zip then you should know where it is.

**Comment by Marimuthu-Dev** [comment]
I had faced same issue, Have resolved by this link https://ferencfbin.medium.com/html-to-pdf-using-go-22ffdb1f1a45
