### ISSUE TITLE
wkhtmltoimage

### ISSUE THREAD

**Issue by Doodlister** [SebastiaanKlippert/go-wkhtmltopdf#36]
I need to convert a html to image. And i notice that the office website of  wkhtmltopdf have offered a tool named wkhtmltoimage.. this porject go-wkhtmltopdf seem only support wkhtmltopdf.. Do you have any plans to support  wkhtmltoimage?

**Comment by SebastiaanKlippert** [comment]
I had that in mind when writing this wrapper, so I think it is possible, but so far I have not tried.
 wkhtmltoimage has some other options, but I have never used it in production and I would need to do some research on the differences. For example, I don't think it supports multiple input pages or reading input from stdin, it has no header and footer options, no TOC options etc.
Maybe that should just be a different wrapper it there are too many differences.

Currently I have no concrete plans, but maybe I can take a look when I am a bit less busy at work in a few weeks.
