### ISSUE TITLE
Get output information

### ISSUE THREAD

**Issue by cheesysam** [SebastiaanKlippert/go-wkhtmltopdf#37]
Calling wkhtmltopdf at a terminal gives output like the following, 

`Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done`

Is there a way to get this out of the go package?

**Comment by SebastiaanKlippert** [comment]
Hmm, it writes that output to Stderr which I only inspect if there was an error. I will create a method to set Stderr to a different writer. Think that might me useful.

**Comment by SebastiaanKlippert** [comment]
I have added method [SetStderr](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.SetStderr) which you can call before calling `Create()` to set any `io.Writer` as the output for `Create()`.

```go
pdfg, err := NewPDFGenerator()
if err != nil {
	log.Fatal(err)
}

pdfg.AddPage(NewPage("https://www.google.com"))

errBuf := new(bytes.Buffer)
	pdfg.SetStderr(errBuf)

err = pdfg.Create()
if err != nil {
	log.Fatal(err)
}

fmt.Println(errBuf.String())
```

```
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done    
```
