### ISSUE TITLE
no buildable source file is found ..

### ISSUE THREAD

**Issue by Almodovar** [SebastiaanKlippert/go-wkhtmltopdf#4]
go get the package but the error message comes out when trying to build the main file

**Comment by SebastiaanKlippert** [comment]
Hi,  

There is no main file. You can run the test or import the package in your own main or application. 

Or do you have problems using the package in another way? If so, include some sample code, but everything you need is included in the samples.

**Comment by Almodovar** [comment]
Thanks for the reply. the problems is caused by the wrong path.

**Comment by SebastiaanKlippert** [comment]
Glad it works, let me know if you have any other issues or questions.
