### ISSUE TITLE
blank output for NewPage("myURL")

### ISSUE THREAD

**Issue by ibantoo** [SebastiaanKlippert/go-wkhtmltopdf#41]
i get blank output  from localhost like "http://localhost:3000/login" this web using React JS
but the url from "https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf" was work, what is the problem ?? :)

**Comment by SebastiaanKlippert** [comment]
Can be anything, I cannot see your localhost page 😉 
Can you try calling wkhtmltopdf directly from commandline and see if that works?

**Comment by ibantoo** [comment]
it was blank as well :), is there any way to make it possible to create pdf from that localhost? @SebastiaanKlippert

**Comment by SebastiaanKlippert** [comment]
You could try  to see if there is any warning printed,
```go
pdfg.SetStderr(os.Stdout)
``` 
Or try to ask someone at wkhtmltopdf, or try a different HTML to PDF converter like Athena PDF or Gotenberg.
