### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by flapan** [SebastiaanKlippert/go-wkhtmltopdf#44]
As I read the newTestPDFGenerator function it adds TOC to the pdfs generated by it, but I don't see it in any of the pdf's created by running the tests? Am I missing something or is something broken with regards to TOC?

**Comment by SebastiaanKlippert** [comment]
There was an issue in wkhtmltopdf where this was indeed broken in version 0.12.5 (the current release).
On my local machine I can see the TOC in 0.12.4, I have just updated my Travis builds to use a dev build of 0.12.6 and is visible there again as well.

So I guess you are using 0.12.5 and are seeing this issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3953
The TOC is on the contents, but not visible.

You can find the dev builds [here](https://builds.wkhtmltopdf.org/0.12.6-dev/) if that helps.
There is already a discussion on the release of 0.12.6 going on here https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4578

**Comment by flapan** [comment]
Cool, thanks for the fix and answer!
