### ISSUE TITLE
Update docs to show how to retrieve internal buffer

### ISSUE THREAD

**Issue by ORESoftware** [SebastiaanKlippert/go-wkhtmltopdf#45]
I don't want to write the PDF to a file - instead I need to attach the PDF to an email. In the docs, it shows:

```golang
       // Create PDF document in internal buffer
	err = pdfg.Create()
	if err != nil {
		log.Fatal(err)
	}


	err = pdfg.WriteFile(pdfFile)  // unnecessary WriteFile method
	if err != nil {
		return err
	}
```

look, people know how to write files, given buffers etc. We don't need helper methods for that. Can you update your docs to show how to retrieve the internal buffer? Thanks for accepting criticism.

**Comment by SebastiaanKlippert** [comment]
You are looking at an example (which is called "simplesample" for a reason), not the docs.

The [docs](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf) show methods [Bytes](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.Bytes) and [Buffer](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.Buffer) which you can use for that.
So if you say 

> look, people know how to write files, given buffers etc. 

Then I don't know why you did not find these? Perhaps they are also "unnecessary" methods?

There is even a [sample in the docs](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#NewPDFGeneratorFromJSON) which shows how to use the buffer you seem to know so well:
```go
fmt.Printf("PDF size %d bytes", pdfgFromJSON.Buffer().Len())
```

Sorry I did not include the exact sample code you need in the readme.
