### ISSUE TITLE
go install does not install binary in expected location :(

### ISSUE THREAD

**Issue by ORESoftware** [SebastiaanKlippert/go-wkhtmltopdf#47]
I run this:

```bash
$ cd $GOPATH/src/github.com/SebastiaanKlippert/go-wkhtmltopdf 
$ go install
```

but no new binary is created in `$GOPATH/bin`

so what's the deal here?
also `go get github.com/SebastiaanKlippert/go-wkhtmltopdf ` does not create the binary either :(

**Comment by SebastiaanKlippert** [comment]
Why do you expect this behaviour? 
There is not even a main.go file, this is service/client for wkhtmltopdf, not a standalone application.
