### ISSUE TITLE
Generate pdf from html using header, body and footer provided in string.

### ISSUE THREAD

**Issue by Pooraa-Chaitanya** [SebastiaanKlippert/go-wkhtmltopdf#49]
We are given with header, body and footer in string variables. Using this, we have to generate pdf in which header and footer remains constant but body dynamically varies according to the data.
Currently, this feature is not available.

Example:
header:= "<html><body>Header</body></html>"
body:= "<html><body>Body</body></html>"
footer:= "<html><body>Footer</body></html>"

fund generatePDF(header, body, footer string){}

**Comment by Pooraa-Chaitanya** [comment]
page.HeaderCenter.Set("I AM THE HEADER")
page.FooterCenter.Set("I AM THE FOOTER")
What the above functions do is simply print the string provided as the parameter in the header and footer.

Suppose I write, page.HeaderCenter.Set(`"<html><body>Header</body></html>"`). This will print `"<html><body>Header</body></html>"` in the header. What I want is to parse the HTML code like strings.NewReader() does.

For example:
func generatePdf() {
	pdfg, err := wkhtmltopdf.NewPDFGenerator()
	if err != nil {
		log.Fatal(err)
	}
	header := `"<html><body>Header</body></html>"`
	body := `"<html>
				<body>
					<table>
					<tbody>
						<tr style="background-color: #f1f1f1; font-size: 12px; height: 39px;">
							<th style="padding: 5px; width: 19px; font-weight: normal;">
								Serial Number
							</th>
							<th style="text-align: left; padding: 5px; font-weight: normal;">
								Products
							</th>
						</tr>
					</tbody>
					</table>
				</body>
			</html>"`
	footer := `"<html><body>Footer</body></html>"`

	page := wkhtmltopdf.NewPageReader(strings.NewReader(body))
	page.HeaderCenter.Set(header)
	page.FooterCenter.Set(footer)

	pdfg.AddPage(page)
	err = pdfg.Create()
	if err != nil {
		log.Fatal(err)
	}

	err = pdfg.WriteFile("./HeaderAndFooter.pdf")
	if err != nil {
		log.Fatal(err)
	}
}

What I want from the above code is to print header and footer at each page and their value will be constant. But the body is a table which can have dynamic rows.  
Suppose the table contains 100 rows and in a single page, only 10 rows can be present with the header and the footer, so, there should be 10 pages created with header and footer in each page along with 10 tables row in the body.

**Comment by SebastiaanKlippert** [comment]
You could use the HeaderHTML and FooterHTML options to set HTML in the header and footer, but that will only accept a URL, so you will need to upload the HTML somewhere, or create an HTTP server in your calling code to serve it.

But you could also not use the wkhtmltopdf header and footer options and do it in your HTML body by setting a fixed page size and using print media types. Something like this https://medium.com/@Idan_Co/the-ultimate-print-html-template-with-header-footer-568f415f6d2a

Anyway, all this is not really related to the Go wrapper which just feeds commandline options to wkhtmltopdf, so I am going to close this issue.

**Comment by Khyme** [comment]
Hello, Sorry for opening this again.

I had issues using footer/header in pageOptions (for example in the doc provided snippet, the footer page count didn't show up for me).
I tried this snippet @SebastiaanKlippert and it fails creating a file.

Using go-wkhtmltopdf v1.7.1 and wkhtmltopdf 0.12.5-1build1
