### ISSUE TITLE
How can I add header and footer in every page

### ISSUE THREAD

**Issue by hg-pooraa** [SebastiaanKlippert/go-wkhtmltopdf#50]
I have used header-html and footer-html tag but facing a issue
![Screenshot from 2020-07-06 15-32-30](https://user-images.githubusercontent.com/62383823/86581677-0baf5780-bf9e-11ea-9dde-77ff22d40532.png) Whole header and hooter is not coming. only some part of from below is only getting printed.
         page := wkhtmltopdf.NewPageReader(bytes.NewReader(htmlCode))
	page.DisableExternalLinks.Set(false)
	page.FooterFontSize.Set(7)
	page.FooterRight.Set("[page]")
	page.HeaderHTML.Set("/usr/local/bin/header.html")
	page.FooterHTML.Set("/usr/local/bin/footer.html")
This is the code I am using.

**Comment by SebastiaanKlippert** [comment]
Can you check if there are any errorlogs?
Easiest way to do so is write StdErr to a buffer, see https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.SetStderr

Maybe it is giving errors that it cannot load the file.

I was looking at this old issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1645 as well.
That might also give you some hints, for eample you need a `<!doctype html>` header, you could use `file://` protocol etc.

But logging StdErr will help as a first step.
I guess you are facing a wkhtmltopdf issue and nothing in my wrapper, but I will try to help if possible 😉

**Comment by hg-pooraa** [comment]
wkhtmltopdf 'body.html' --header-html 'header.html' --footer-html 'footer.html' 'test.pdf'

I am running this command. Any this is working perfect. So there is no wkhtmltopdf issue

**Comment by SebastiaanKlippert** [comment]
Ok, thanks for the info, that is good to know.

It might still be a wkhtmltopdf issue, but I would need to see the logs to get some more info.
Can you post these?

You could also try this Go code and load the body.html you mentioned above directly.

```go
page := wkhtml.NewPage("body.html")
page.DisableExternalLinks.Set(false)
page.FooterFontSize.Set(7)
page.FooterRight.Set("[page]")
page.HeaderHTML.Set("/usr/local/bin/header.html")
page.FooterHTML.Set("/usr/local/bin/footer.html")
```

The code you originally posted uses stdin and not a file from disk.
This changes the current working dir in wkhtmltopdf to temp for some reason, see https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3014

I guess that is your issue, but to confirm you need to check or post the logs.

If loading the body directly works, you could try to specify the header and footer using a file scheme:
`page.HeaderHTML.Set("file:///usr/local/bin/header.html")`

**Comment by hg-pooraa** [comment]
I have checked the logs. No error. and this code is also giving the same result. Please help me out

**Comment by hg-pooraa** [comment]
The code you provided also did't worked and there is no err logs

**Comment by SebastiaanKlippert** [comment]
I did a quick check and wrote a test to try and duplicate.
On my Windows machine this code works as expected in wkhtmltopdf 0.12.6 and 0.12.4:

```go
func TestHFHTML(t *testing.T) {
	pdfg, err := NewPDFGenerator()
	if err != nil {
		t.Fatal(err)
	}

	html := `<!doctype html>
<body>
I am the body!
</body>`

	//page := NewPage(`D:\body.html`)
	page := NewPageReader(strings.NewReader(html))
	page.DisableExternalLinks.Set(false)
	page.FooterFontSize.Set(7)
	page.FooterRight.Set("[page]")
	page.HeaderHTML.Set(`D:\header.html`)
	page.FooterHTML.Set(`D:\footer.html`)

	pdfg.AddPage(page)

	err = pdfg.Create()
	if err != nil {
		t.Fatal(err)
	}

	err = pdfg.WriteFile(`D:\TestHFHTML.pdf`)
	if err != nil {
		t.Fatal(err)
	}
}

```

This produces attached PDF [TestHFHTML.pdf](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/4885910/TestHFHTML.pdf)

The commented code, where I put the body on disk also works.

If you want to test, I have included the files here (with .txt extension because github does not accept html files).
[footer.html.txt](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/4885811/footer.html.txt)
[body.html.txt](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/4885813/body.html.txt)
[header.html.txt](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/4885901/header.html.txt)

So any issues you have are probably within your HTML files or maybe you can reproduce with above code on your OS,

**Comment by hg-pooraa** [comment]
Ok thank you. Its working

**Comment by maeglindeveloper** [comment]
@SebastiaanKlippert , I did test the code above, but this is not working.
Any way you can double check this on your side? 
thank you so much

**Versions:**
wkhtmltopdf 0.12.6 
go-wkhtmltopdf v1.7.2

I'm using linux (fedora).
