### ISSUE TITLE
Could not render html in pdf

### ISSUE THREAD

**Issue by hg-pooraa** [SebastiaanKlippert/go-wkhtmltopdf#52]
suppose my instruction is `<p>Hi,</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><em>My</em> <u>name</u> is <strong>Bijo</strong>.</p>`

I want is to get parsed into HTMl and then get printed on pdf

but the output is 
![Screenshot from 2020-07-17 18-19-54](https://user-images.githubusercontent.com/62383823/87787965-24e7bc00-c85a-11ea-8de6-710ac4f80bb8.png)

Please help me out.

**Comment by SebastiaanKlippert** [comment]
😄 
What happens when you render the HTML in a browser?
It looks like HTML code in a HTML document so I see no eason why it would not work, you would need to check your HTML code I guess.
