### ISSUE TITLE
Warning: Blocked access to file

### ISSUE THREAD

**Issue by kma138** [SebastiaanKlippert/go-wkhtmltopdf#55]
I'm trying to generate a PDF using .Create() , and the default options using NewPDFGenerator() , and running into this below issue:

```
Warning: Blocked access to file <omitted directory>/pdf.css
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol \"about\" is unknown\n[============================================>               
]
``` 

The same codeblock works on a different machine. Am I missing any options? I checked the generator's Cover.pageOptions which has DisableLocalFileAccess set to false.

**Comment by SebastiaanKlippert** [comment]
These is a warning and an error, maybe they are not related, the other machine might give te same warning, but not the error.
Although it seems they are related, there is an issue for this on wkhtmltopdf https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4460 
That also mentions the enable local file access flag.

You should try setting `page.EnableLocalFileAccess(true)` Note that this is a page option on the input HTML, not the cover options you were using.
Currently there are both EnableLocalFileAccess and DisableLocalFileAccess options, usually there is only one boolean option, depending on the default.
But the default behaviour changed in 0.12.6, so it could also be that you have one machine running 0.12.5 and one on 0.12.6.

Anyway, check if it works with `EnableLocalFileAccess`.

**Comment by kma138** [comment]
It worked! I also had to update my go-wkhtmltopdf version to get that option. The go version between mine and the working deployment (on production) is also different so that might explain why it was working there.  Thank you

**Comment by SebastiaanKlippert** [comment]
Thanks for the feedback

**Comment by PhilterPaper** [comment]
Up through wkHTMLtoPDF 0.12.5, the default was to _enable_ local file access. As of 0.12.6, the default is to _disable_ local file access for security reasons.

**Comment by relogz** [comment]
try EnableLocalFileAccess.Set(true)
it works for me
