### ISSUE TITLE
some css stylings are not reflecting in the generated pdf

### ISSUE THREAD

**Issue by aptnrg007** [SebastiaanKlippert/go-wkhtmltopdf#67]
I'm facing some issues with the css styling, after the pdf generation the stylings are not reflected... even though its there in the html file. ex- font-weight, transform.

is there something im missing?

**Comment by SebastiaanKlippert** [comment]
Probably not, do the same thing on commandline wkhtmltopdf, if it looks the same it is not in my library.
One thing you could try first is set `EnableLocalFileAccess(true)` toi make sure it also loads anything on disk like external CSS or fonts.
