### ISSUE TITLE
`background-color` css property is working in wkhtmltopdf command, but not in go-wkhtmltopdf

### ISSUE THREAD

**Issue by gouthampc** [SebastiaanKlippert/go-wkhtmltopdf#68]
Command used while generating pdf via wkhtmltopdf

```wkhtmltopdf  --enable-local-file-access file:///receipt.html receipt.pdf```

Options given for wkhtmltopdf
```	
pageOptions := NewPageOptions()
pageOptions.EnableLocalFileAccess.Set(true)
pageOptions.LoadErrorHandling.Set("ignore")

pageReader := &PageReader{
    Input:       templateContents,
    PageOptions: pageOptions,
}
```

PDF generated by htmltopdf
[receipt.pdf](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/6969543/receipt.pdf)

PDF generated by go-wkhtmltopdf
[receipt.pdf](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/files/6969530/receipt.pdf)

Do I need to provide any special option while using go-wkhtmltopdf to make background-color property work?

**Comment by SebastiaanKlippert** [comment]
Hi, that is unexpected, but I saw a simliar issue here https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/67

There should not be a difference in the go package.

The only thing I see from your example is that you are reading from a file when you call wkhtmltopdf directly and from stdin in the Go code.

Can you try in your terminal `cat receipt.html | wkhtmltopdf --enable-local-file-access - receipt.pdf`

If that produces the same result as in the go code, it is a bug in wkhtmltopdf when reading from stdin, but maybe there is a workaround. If it works as expected then I would love to see the source HTML file to see if I can reproduce.

**Comment by gouthampc** [comment]
Looks like a mistake from my end. I was referring css file path relative to html file. Since the html is in memory in go code, it was not able to access the css file. Changing css file path to absolute path fixed the issue. Thank you.

**Comment by SebastiaanKlippert** [comment]
No problem, thanks for letting me know.
