### ISSUE TITLE
Unable to generate more than one page while reading different htmls

### ISSUE THREAD

**Issue by keepschanging** [SebastiaanKlippert/go-wkhtmltopdf#7]
I am trying to generate a pdf with one page from one html and the second page from another html. But the second page never gets printed. Its comes blank. When I try and create 2 different pdfs then they are created perfectly. Just not in a single one. Can you please share code for such a scenario?

**Comment by keepschanging** [comment]
Had to write the html into a new file and use NewPage. Doesn't work with NewPageReader and bytes.

**Comment by SebastiaanKlippert** [comment]
Correct. This is also stated in the docs for type PageReader.

> You can add only one Page from a reader 

The reason is that I can only pass one page from stdin to wkhtmltpdf as far as I know. But your workaround sound good 👍
