### ISSUE TITLE
pdfg.Create() returns error "Loading pages: ..."

### ISSUE THREAD

**Issue by c3098051** [SebastiaanKlippert/go-wkhtmltopdf#70]
go version: 1.16
wkhtmltopdf version: 0.12.5 (with patched qt)
github.com/SebastiaanKlippert/go-wkhtmltopdf: v.1.7.1

I can generate pdf by using a command on a server 

```sh
wkhtmltopdf --javascript-delay 2000 --debug-javascript --enable-javascript test.html sample.pdf
```
However, via go-wkhtmltopdf returns an error with the string as below. 
Any idea what I've done wrong?

```code
	f, err := os.Create(htmlfilename)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// write to htmlfile
	if _, err := f.WriteString(html); err != nil {
		return "", err
	}
	defer os.Remove(htmlfilename)

	// crate page from html
	page := wkhtmltopdf.NewPage(htmlfilename)
	page.NoStopSlowScripts.Set(true)
	page.JavascriptDelay.Set(2000)
	page.FooterCenter.Set("[page] of [topage]")
	page.FooterFontSize.Set(10)
	page.Zoom.Set(1)

	// Add to document
	// Set global options
	// Create new PDF generator
	pdfg, err := wkhtmltopdf.NewPDFGenerator()
	if err != nil {
		logger.Infof("failed to newPDFGenerator: %v", err)
		return "", err
	}
	pdfg.Dpi.Set(300)
	pdfg.Orientation.Set(wkhtmltopdf.OrientationPortrait)
	pdfg.Grayscale.Set(false)
	pdfg.AddPage(page)

	// pdfg.MarginBottom.Set(0)
	pdfg.MarginTop.Set(0)
	pdfg.MarginLeft.Set(0)
	pdfg.MarginRight.Set(0)

	// Create PDF document in internal buffer
	err = pdfg.Create()

	// ignore err
	// if err != nil {
	// 	logger.Infof("failed to create: %v", err)
	// 	return "", err
	// }

```

Loading pages (1/6)\n[\u003e                                                           ] 0%\r[======\u003e                                                     ] 10%\r[=========\u003e                                                  ] 15%\r[================\u003e                                           ] 28%\r[==================\u003e                                         ] 30%\r[=====================\u003e                                      ] 36%\r[=======================\u003e                                    ] 39%\r[=========================\u003e                                  ] 43%\r[==========================\u003e                                 ] 44%\r[============================\u003e                               ] 47%\r[============================\u003e                               ] 47%\r[==============================\u003e                             ] 51%\r[===================================\u003e                        ] 59%\r[======================================================\u003e     ] 90%\r[======================================================\u003e     ] 90%\r[============================================================] 100%\rCounting pages (2/6)                                               \n[============================================================] Object 1 of 1\rResolving links (4/6)                                                       \n[============================================================] Object 1 of 1\rLoading headers and footers (5/6)                                           \nPrinting pages (6/6)\n[\u003e                                                           ] Preparing\r[===============\u003e                                            ] Page 1 of 4\r[==============================\u003e                             ] Page 2 of 4\r[=============================================\u003e              ] Page 3 of 4\r

**Comment by SebastiaanKlippert** [comment]
Hi, that seems hard to debug for me if don't know the HTML source, but there should be no differences between the Go library and calling wkhtmltopdf directly in this case.

The only thing I see in the code is that you are not setting the `--debug-javascript` flag, that would be `page.DebugJavascript(true)`

What is the behaviour you are seeing? The output you pasted does not contain an error, does it freeze?
And why did you choose to ignore the last error, does that say anything?

**Comment by c3098051** [comment]
Hi SebastiaanKlippert. You were right. There's no difference between Go library, and calling wkhtmltopdf directly. 
When I found the command with args from the process list, there's an argument --dpi 300. In fact, this is working in my local, but causing a "Killed" issue on the production server. This is not an issue from the library, so I will self-close the issue.
