### ISSUE TITLE
Error on headless configuration

### ISSUE THREAD

**Issue by and-hom** [SebastiaanKlippert/go-wkhtmltopdf#77]
```
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

Here is solution https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4495#issuecomment-572892937

Have to call this code before running
```
	if err := os.Setenv("QT_QPA_PLATFORM", "offscreen"); err != nil {
		log.Error("Can't set environment value QT_QPA_PLATFORM for headless wkhtmltopdf execution: ", err)
	}
```

Would be nice to add it inside the library

```
5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SebastiaanKlippert** [comment]
You can already set this environment variable in your calling Go program, so I don't see why this should be added to this wrapper, it is very machine specific, not sure it changes behaviour on other machines.

But thanks for the report, useful to know.
