### ISSUE TITLE
Pass bytes value instead of url or file path

### ISSUE THREAD

**Issue by Limoli** [SebastiaanKlippert/go-wkhtmltopdf#8]
I would pass a value containing already the HTML and CSS in string format instead passing a link or a file path.

**Comment by SebastiaanKlippert** [comment]
Unless I am misunderstanding your suggestion: You can already do that using PageReader.
https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PageReader 

This reads from an io.Reader.

For example, if you have a bytes slice called `buf`, you can do this:
```go
buf := []byte("<html>Hi</html>")
pdfgen.AddPage(NewPageReader(bytes.NewReader(buf)))
```

**Comment by Limoli** [comment]
Yeah! At the end I tried too with the page reader and now it does what I expect.
