### ISSUE TITLE
Page break ignored on long text from td

### ISSUE THREAD

**Issue by srabieb** [SebastiaanKlippert/go-wkhtmltopdf#83]
That's the problem I have.
i have long content on td and page-break doesn't work here.
`table, tr, td, th, tbody, thead, tfoot { page-break-inside: avoid !important; }`
that's not working to me

![image](https://user-images.githubusercontent.com/26784284/167765180-84c764ac-11ad-40b2-95c3-437383d4bfe1.png)

**Comment by SebastiaanKlippert** [comment]
How would you propose this to be fixed? Your text is longer than the page.
In any case, it is not an issue in my wrapper, you would need to look at https://github.com/wkhtmltopdf/wkhtmltopdf
