### ISSUE TITLE
Getting QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once

### ISSUE THREAD

**Issue by kay-master** [SebastiaanKlippert/go-wkhtmltopdf#88]
while using the package as a service am getting this error when doing subsequent requests to the service

``` 
2022/06/01 19:13:38 QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loading page (1/2)
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500&display=swap")
```

on am not sure what to do

**Comment by SebastiaanKlippert** [comment]
I have never seen that error before to be honest.
A Google search leads me to either an outdated version of wkhtmltopdf or you are running it in a Docker container without the correct dependencies.

Can you share what version of wkhtmltopdf  you are using and in what OS you are running it and if that is in Docker?

And do you also get this error if you run wkhtmltopdf directly or just from my library?

Last question:  With "subsequent requests to the service", what do you mean exactly? Do you have a go service that runs once and does multiple calls to wkhtmltopdf or do you run a go program multiple times? And are those parallel calls or do you wait until the previous call is completed?

Thanks
