### ISSUE TITLE
Does it works with raw HTML, instead of a file?

### ISSUE THREAD

**Issue by juancaacuna** [SebastiaanKlippert/go-wkhtmltopdf#9]
Does it works with raw HTML, instead of a file?

**Comment by SebastiaanKlippert** [comment]
Doe you mean like in #8 ?

**Comment by juancaacuna** [comment]
Yeah that one! I didn't see that response. It would be cool to add that part to the readme.
Thanks :)

**Comment by SebastiaanKlippert** [comment]
NP, I have updated the readme to make this more clear since you are not the first person to ask.
