### ISSUE TITLE
Is there any native binding for the wkhtmltopdf library?

### ISSUE THREAD

**Issue by abhisekp-impeller** [SebastiaanKlippert/go-wkhtmltopdf#97]
This can provide interoperability and help in faster response without process creation overhead.

**Comment by SebastiaanKlippert** [comment]
Nope, I will not build that

**Comment by Jackysi** [comment]
> Yes, too much hassle, C dependencies, etc. And with wkhtmltopdf no longer supported it does make sense https://wkhtmltopdf.org/status.html
> 
> In addition to that, I think most people are running this in webserver environments anyway, so I don't really see the need to bind to it from Go, in a server environment you might just as well spawn a new process that you can easily kill if something fails.
> 
> But I am not here to tell anyone not to create the bindings, just that I myself will not do it :)

Completely understand. Was just wondering what was the reason. Thanks for taking the time and for your response. 

Did you maybe stumble across an alternative that would still be actively developed?

**Comment by SebastiaanKlippert** [comment]
There are a few, but I don't know all of them.
We moved to https://go-rod.github.io

**Comment by Jackysi** [comment]
> There are a few, but I don't know all of them. We moved to https://go-rod.github.io Specifically https://pkg.go.dev/github.com/go-rod/rod/lib/proto#PagePrintToPDF

That is awesome. Thanks! Looks super useful!
