### ISSUE TITLE
How to use custom font without rasterizing the font?

### ISSUE THREAD

**Issue by abhisekp-impeller** [SebastiaanKlippert/go-wkhtmltopdf#98]
I can use the following but it rasterizes the font while creating the PDF. And it is not selectable in the pdf.

```html
<link href="https://fonts.googleapis.com/css2?family=Fasthand&display=swap" rel="stylesheet">
```

**Comment by SebastiaanKlippert** [comment]
I have no idea, you might want to ask at https://github.com/wkhtmltopdf/wkhtmltopdf
